#!/usr/bin/env python3
"""Generate the Digital Marketing directory tree from the capability map.

The tree is the requested Phase-1 structure. Each directory carries a generated README
listing the capabilities it owns and their real build status, so an empty directory
cannot read as a built subsystem — the honest version of scaffolding.

Generated, never hand-edited: the map stays the single source of truth, and
`--check` fails if the tree has drifted from it.

    python3 scripts/build_tree.py            # write the tree
    python3 scripts/build_tree.py --check    # fail if stale
    python3 scripts/build_tree.py --selftest
"""
from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# area -> (subdirectories, capability-map domains that feed it)
AREAS: dict[str, tuple[tuple[str, ...], tuple[str, ...]]] = {
    "intelligence": (
        ("market", "customer-voc", "competitor", "demand", "discovery",
         "product-opportunities"),
        ("1_market_intelligence",),
    ),
    "strategy": (
        ("segmentation", "positioning", "awareness", "offers", "messaging", "persuasion"),
        ("2_strategy",),
    ),
    "creative": (
        ("hooks", "families", "genome", "proof", "synthetic-media"),
        ("3_creative",),
    ),
    "channels": (
        ("seo", "ai-search", "content", "social", "email", "paid-media", "outbound",
         "affiliate", "partnerships"),
        ("4_distribution",),
    ),
    "conversion": (
        ("landing-pages", "social-profiles", "conversations", "cro", "qualification"),
        ("5_conversion",),
    ),
    "lifecycle": (
        ("crm", "nurture", "retention", "expansion"),
        ("6_lifecycle_revenue",),
    ),
    "measurement": (
        ("attribution", "cac", "ltv", "contribution-profit", "allowable-cac"),
        ("7_measurement_economics",),
    ),
    "operator": (
        ("skills", "policies", "authority", "audit"),
        ("8_ai_growth_engineering",),
    ),
}

BANNER = "<!-- generated by scripts/build_tree.py — do not hand-edit -->"


def render_area(area: str, subdirs: tuple[str, ...], domains: tuple[str, ...], data: dict) -> str:
    lines = [BANNER, "", f"# {area}", ""]
    caps: dict[str, str] = {}
    titles = []
    for key in domains:
        domain = data["domains"][key]
        titles.append(domain["title"])
        caps.update(domain["capabilities"])

    built = sum(1 for s in caps.values() if s == "IMPLEMENTED")
    lines += [
        f"**{', '.join(titles)}** — {built} of {len(caps)} capabilities implemented.",
        "",
        "This directory is a place in the taxonomy, not a claim that code lives here. "
        "Working code lives in `src/ai_growth_engineering/`; what is real is recorded "
        "in `capability_map.json` and reflected below.",
        "",
        "## Sub-areas",
        "",
    ]
    lines += [f"- `{s}/`" for s in subdirs]
    lines += ["", "## Capabilities and honest status", ""]
    lines += ["| Capability | Status |", "| --- | --- |"]
    for name, status in sorted(caps.items(), key=lambda kv: (kv[1] != "IMPLEMENTED", kv[0])):
        lines.append(f"| `{name}` | {status} |")
    lines += [
        "",
        "`IMPLEMENTED` = code exists and a deterministic test covers it. "
        "`SPECIFIED` = written as a skill, template or policy, not executable. "
        "`HYPOTHESIS` = named and understood, nothing built.",
        "",
    ]
    return "\n".join(lines)


def build(root: Path, data: dict, *, check: bool = False) -> list[str]:
    stale: list[str] = []
    for area, (subdirs, domains) in AREAS.items():
        wanted = render_area(area, subdirs, domains, data)
        readme = root / area / "README.md"
        if check:
            if not readme.exists() or readme.read_text(encoding="utf-8") != wanted:
                stale.append(str(readme.relative_to(root)))
            continue
        for sub in subdirs:
            (root / area / sub).mkdir(parents=True, exist_ok=True)
            keep = root / area / sub / ".gitkeep"
            if not keep.exists():
                keep.write_text("", encoding="utf-8")
        readme.write_text(wanted, encoding="utf-8")
    return stale


def selftest() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        data = json.loads((ROOT / "capability_map.json").read_text(encoding="utf-8"))

        assert build(root, data, check=True), "a missing tree must report stale"
        build(root, data)
        assert build(root, data, check=True) == [], "a freshly built tree must be clean"

        # Every declared area exists with every sub-area.
        for area, (subdirs, _) in AREAS.items():
            assert (root / area / "README.md").is_file(), area
            for sub in subdirs:
                assert (root / area / sub).is_dir(), f"{area}/{sub}"

        # A README must not claim more than the map does.
        text = (root / "measurement" / "README.md").read_text(encoding="utf-8")
        assert "HYPOTHESIS" in text, "unbuilt capabilities must stay visible"

        # Drift is detected, not silently re-blessed.
        (root / "creative" / "README.md").write_text("hand edited", encoding="utf-8")
        assert build(root, data, check=True), "hand-edited README must report stale"
    print(f"build_tree selftest: 5 assertions passed across {len(AREAS)} areas")
    return 0


def main(argv: list[str]) -> int:
    if "--selftest" in argv:
        return selftest()
    data = json.loads((ROOT / "capability_map.json").read_text(encoding="utf-8"))
    if "--check" in argv:
        stale = build(ROOT, data, check=True)
        if stale:
            print("tree is stale against capability_map.json:")
            for path in stale:
                print(f"  {path}")
            print("\nrun: python3 scripts/build_tree.py")
            return 1
        print(f"tree: OK — {len(AREAS)} areas match capability_map.json")
        return 0
    build(ROOT, data)
    print(f"wrote {len(AREAS)} area READMEs and their sub-areas")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
