#!/usr/bin/env python3
"""Docs check — a number in the documentation must be the number in the state.

Prose may carry a live figure only inside a marker:

    <!-- state:capabilities.total -->215<!-- /state -->

The key is a dotted path into docs/STATE.json (generated by `age snapshot --write`). This check fails
when a marker disagrees with the state file, when the state file's capability section disagrees with
capability_map.json, when a named historical narrative has lost its HISTORICAL banner, and — only
where a local store exists — when the state file's store section disagrees with the store. Without a
store it says the store section was NOT CHECKED; it never reports that as a pass.

    python3 scripts/docs_check.py            # check
    python3 scripts/docs_check.py --sync     # rewrite marker values from docs/STATE.json
    python3 scripts/docs_check.py --selftest
"""
from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from ai_growth_engineering.snapshot import capability_state, flatten, store_state  # noqa: E402

STATE = ROOT / "docs" / "STATE.json"
STORE = ROOT / ".age" / "growth.db"
MARKER = re.compile(r"<!-- state:([A-Za-z0-9_.()\-]+) -->(.*?)<!-- /state -->")
# Fewer markers than this means the check found almost nothing to check.
MIN_MARKERS = 4
BANNER = "**HISTORICAL**"
# Narrative that was true when written and is kept as written. Each must say so at the top.
HISTORICAL = (
    "experiments/EXP-ACQ-0003/EXECUTION-COHORT.md",
    "experiments/EXP-ACQ-0003/EXECUTION-MODE.md",
    "experiments/EXP-ACQ-0003/IDENTITY-VERIFICATION.md",
    "experiments/EXP-ACQ-0006/README.md",
    "docs/FIRST_30_DAYS.md",
    "docs/OFFER.md",
)


def tracked_markdown(root: Path) -> list[Path]:
    out = subprocess.run(["git", "-C", str(root), "ls-files", "*.md"], capture_output=True, text=True)
    return [root / line for line in out.stdout.splitlines() if line and (root / line).exists()]


def marker_count(paths: list[Path]) -> int:
    return sum(len(MARKER.findall(p.read_text(encoding="utf-8"))) for p in paths)


def _value(value) -> str:
    return json.dumps(value) if isinstance(value, (bool, type(None))) else str(value)


def check_markers(paths: list[Path], state: dict) -> list[str]:
    flat = flatten(state)
    problems = []
    for path in paths:
        for key, shown in MARKER.findall(path.read_text(encoding="utf-8")):
            if key not in flat:
                problems.append(f"{path.name}: marker {key!r} names nothing in the state file")
            elif shown.strip() != _value(flat[key]):
                problems.append(f"{path.name}: {key} shows {shown.strip()!r}, the state says {_value(flat[key])!r}")
    return problems


def sync_markers(paths: list[Path], state: dict) -> int:
    flat, changed = flatten(state), 0
    for path in paths:
        text = path.read_text(encoding="utf-8")
        new = MARKER.sub(lambda m: (f"<!-- state:{m.group(1)} -->{_value(flat[m.group(1)])}<!-- /state -->"
                                    if m.group(1) in flat else m.group(0)), text)
        if new != text:
            path.write_text(new, encoding="utf-8")
            changed += 1
    return changed


def check_capabilities(state: dict) -> list[str]:
    live = capability_state()
    recorded = state.get("capabilities") or {}
    return [f"capabilities.{k}: state file says {recorded.get(k)!r}, capability_map.json says {v!r}"
            for k, v in live.items() if recorded.get(k) != v]


def check_store(state: dict, db_path: str | Path) -> tuple[list[str], bool]:
    """Compare against a copy, so checking never migrates or writes the real store."""
    if not Path(db_path).exists():
        return [], False
    with tempfile.TemporaryDirectory() as tmp:
        copy = Path(tmp) / "store.db"
        shutil.copy(db_path, copy)
        live = flatten(store_state(str(copy)))
    recorded = flatten(state.get("store") or {})
    keys = sorted(set(live) | set(recorded))
    return [f"store.{k}: state file says {recorded.get(k)!r}, the store says {live.get(k)!r}"
            for k in keys if live.get(k) != recorded.get(k)], True


def check_historical(root: Path) -> list[str]:
    problems = []
    for name in HISTORICAL:
        path = root / name
        if not path.exists():
            problems.append(f"{name}: listed as historical but missing")
        elif BANNER not in "\n".join(path.read_text(encoding="utf-8").splitlines()[:6]):
            problems.append(f"{name}: historical narrative without a {BANNER} banner in its first lines")
    return problems


def selftest() -> int:
    checks = 0
    live = capability_state()
    state = {"capabilities": live, "store": {"events": {"effective": 3}}}
    with tempfile.TemporaryDirectory() as tmp:
        doc = Path(tmp) / "d.md"
        doc.write_text(f"<!-- state:capabilities.total -->{live['total']}<!-- /state -->", encoding="utf-8")
        assert check_markers([doc], state) == [], "a matching marker must pass"
        checks += 1
        doc.write_text("<!-- state:capabilities.total -->1<!-- /state -->", encoding="utf-8")
        assert check_markers([doc], state), "a wrong marker must fail"
        checks += 1
        doc.write_text("<!-- state:store.events.nope -->3<!-- /state -->", encoding="utf-8")
        assert check_markers([doc], state), "an unknown key must fail"
        checks += 1
        assert sync_markers([doc], {"store": {"events": {"nope": 4}}}) == 1 and ">4<" in doc.read_text()
        checks += 1
    assert check_capabilities({"capabilities": dict(live, total=live["total"] + 1)}), "a stale inventory must fail"
    checks += 1
    assert check_store(state, "/nonexistent/store.db") == ([], False), "no store is not checked, not passed"
    checks += 1
    print(f"docs_check selftest: {checks} assertions passed")
    return 0


def main(argv: list[str]) -> int:
    if "--selftest" in argv:
        return selftest()
    if not STATE.exists():
        print(f"docs_check: {STATE.relative_to(ROOT)} is missing; run `age snapshot --write docs/STATE.json`",
              file=sys.stderr)
        return 1
    state = json.loads(STATE.read_text(encoding="utf-8"))
    docs = tracked_markdown(ROOT)
    if "--sync" in argv:
        print(f"docs_check: rewrote markers in {sync_markers(docs, state)} file(s)")
        return 0
    count = marker_count(docs)
    problems = check_capabilities(state) + check_markers(docs, state) + check_historical(ROOT)
    store_problems, store_checked = check_store(state, STORE)
    problems += store_problems
    if count < MIN_MARKERS:
        problems.append(f"only {count} state markers found (expected at least {MIN_MARKERS}); a check that "
                        "reads nothing has not run")
    if problems:
        print(f"docs_check: {len(problems)} problem(s)", file=sys.stderr)
        for p in problems:
            print(f"  {p}", file=sys.stderr)
        print("\nRegenerate with `make snapshot` then `make docs-sync`; never retype a number.", file=sys.stderr)
        return 1
    store_note = "store section matches the local store" if store_checked else \
        "store section NOT CHECKED (no local store at .age/growth.db)"
    print(f"docs_check: {count} markers in {len(docs)} files match docs/STATE.json; capability inventory matches "
          f"capability_map.json; {len(HISTORICAL)} historical files bannered; {store_note}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
